"""Trendora research core (M13), retrieval (M14), and application service (M15).

Deterministic, in-memory domain contracts for the evidence-backed research
direction (docs/14, docs/15, docs/16, docs/17): ``ResearchQuery``, platform
capability declarations, coverage resolution, the ``ResearchRun`` lifecycle,
YouTube-first retrieval producing normalized in-memory references, and the
synchronous application service the HTTP adapter calls. No persistence, no LLM.
"""

from trendora.research.ai_execution import GroundedInterpretationService
from trendora.research.ai_provider import (
    AIInterpretationProvider,
    AIProviderConfig,
    DEFAULT_TIMEOUT_SECONDS,
    MAX_TOKENS,
    SYSTEM_PROMPT,
    OpenAICompatibleInterpretationProvider,
    build_ai_provider_config,
    build_grounded_request,
    evidence_pack_to_payload,
    request_controls,
)
from trendora.research.application import ResearchApplicationService
from trendora.research.capabilities import (
    KNOWN_SOURCE_CODES,
    default_declarations,
    required_capabilities,
)
from trendora.research.evidence import (
    AnalysisBasis,
    ClaimType,
    ContentObservation,
    EvidenceFact,
    EvidenceField,
    ObservationType,
    ReferenceAnalysis,
    ReferenceId,
    analyze_reference,
    analyze_references,
    extract_evidence,
    reference_id,
)
from trendora.research.exceptions import (
    ResearchAggregationError,
    ResearchAIProviderError,
    ResearchAIProviderNotConfiguredError,
    ResearchAIResponseError,
    ResearchError,
    ResearchInterpretationError,
    ResearchNoCoverageError,
    ResearchSourceNotConfiguredError,
    ResearchStateError,
    ResearchValidationError,
)
from trendora.research.interpretation import (
    AIInterpretation,
    EvidencePack,
    FactCitation,
    InterpretationResult,
    ModelProvenance,
    ObservationCitation,
    PatternCitation,
    interpretation_analysis_basis,
    validate_citations,
    validate_interpretations,
)
from trendora.research.ideation import (
    AIIdeationProvider,
    ContentBrief,
    ContentIdea,
    GroundedIdeationService,
    IdeationContext,
    IdeationResult,
    OpenAICompatibleIdeationProvider,
    SYSTEM_IDEATION_PROMPT,
    build_grounded_ideation_request,
    validate_ideation_result,
)
from trendora.research.models import (
    DEFAULT_RESULT_LIMIT,
    DEFAULT_SOURCE_CODES,
    MAX_RESULT_LIMIT,
    MARKET_CODES,
    CoverageCompleteness,
    CoverageReason,
    CoverageStatus,
    MarketBasis,
    PlatformCapability,
    ResearchCoverage,
    ResearchMetrics,
    ResearchQuery,
    ResearchReference,
    ResearchRun,
    ResearchRunStatus,
    SourceCapabilities,
    SourceCoverage,
    validate_research_query,
)
from trendora.research.patterns import (
    BOOLEAN_OBSERVATION_TYPES,
    PatternAggregate,
    aggregate_patterns,
)
from trendora.research.reporting import (
    ResearchReport,
    ResearchReportService,
    ResearchReportStatus,
    build_research_report_service,
    validate_research_report,
)
from trendora.research.service import ResearchCapabilityResolver
from trendora.research.strategy import (
    AIStrategyProvider,
    ContentGap,
    GroundedStrategyService,
    Opportunity,
    OpenAICompatibleStrategyProvider,
    StrategicContext,
    StrategicResult,
    SYSTEM_STRATEGIC_PROMPT,
    build_grounded_strategy_request,
    validate_strategic_result,
)
from trendora.research.youtube import YouTubeResearchRetriever

__all__ = [
    "AIIdeationProvider",
    "AIInterpretation",
    "AIInterpretationProvider",
    "AIProviderConfig",
    "AIStrategyProvider",
    "AnalysisBasis",
    "BOOLEAN_OBSERVATION_TYPES",
    "ClaimType",
    "ContentBrief",
    "ContentGap",
    "ContentIdea",
    "ContentObservation",
    "DEFAULT_RESULT_LIMIT",
    "DEFAULT_SOURCE_CODES",
    "DEFAULT_TIMEOUT_SECONDS",
    "EvidenceFact",
    "EvidenceField",
    "EvidencePack",
    "FactCitation",
    "GroundedIdeationService",
    "GroundedInterpretationService",
    "GroundedStrategyService",
    "IdeationContext",
    "IdeationResult",
    "InterpretationResult",
    "KNOWN_SOURCE_CODES",
    "MAX_RESULT_LIMIT",
    "MAX_TOKENS",
    "MARKET_CODES",
    "ModelProvenance",
    "ObservationCitation",
    "ObservationType",
    "OpenAICompatibleIdeationProvider",
    "OpenAICompatibleInterpretationProvider",
    "OpenAICompatibleStrategyProvider",
    "Opportunity",
    "PatternAggregate",
    "PatternCitation",
    "ReferenceAnalysis",
    "ReferenceId",
    "ResearchAggregationError",
    "ResearchAIProviderError",
    "ResearchAIProviderNotConfiguredError",
    "ResearchAIResponseError",
    "ResearchInterpretationError",
    "ResearchReport",
    "ResearchReportService",
    "ResearchReportStatus",
    "StrategicContext",
    "StrategicResult",
    "SYSTEM_IDEATION_PROMPT",
    "SYSTEM_PROMPT",
    "SYSTEM_STRATEGIC_PROMPT",
    "aggregate_patterns",
    "analyze_reference",
    "analyze_references",
    "build_ai_provider_config",
    "build_grounded_ideation_request",
    "build_grounded_request",
    "build_grounded_strategy_request",
    "build_research_report_service",
    "evidence_pack_to_payload",
    "extract_evidence",
    "interpretation_analysis_basis",
    "reference_id",
    "request_controls",
    "validate_citations",
    "validate_ideation_result",
    "validate_interpretations",
    "validate_research_report",
    "validate_strategic_result",
    "CoverageCompleteness",
    "CoverageReason",
    "CoverageStatus",
    "MarketBasis",
    "PlatformCapability",
    "ResearchCapabilityResolver",
    "ResearchCoverage",
    "ResearchError",
    "ResearchMetrics",
    "ResearchNoCoverageError",
    "ResearchQuery",
    "ResearchReference",
    "ResearchRun",
    "ResearchRunStatus",
    "ResearchSourceNotConfiguredError",
    "ResearchStateError",
    "ResearchValidationError",
    "ResearchApplicationService",
    "SourceCapabilities",
    "SourceCoverage",
    "YouTubeResearchRetriever",
    "default_declarations",
    "required_capabilities",
    "validate_research_query",
]
