"""P3 Slice A: canonical fingerprinting, strict recovery validation, save replay.

Fully offline and mocked. The database engine is never built; the save path
runs against a recording fake session, and the strict validator is exercised
directly. The JavaScript round-trip fixture is generated by an installed Node
binary with fictional data only.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import uuid
from datetime import date, datetime, timezone
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch
from uuid import UUID

import pytest
from fastapi.testclient import TestClient

from tests.support.app import create_test_app
from tests.unit.test_research_reporting import _query, _report_service
from trendora.api.report_snapshot import (
    ReportSnapshot,
    canonical_snapshot_bytes,
    snapshot_fingerprint,
)
from trendora.api.research_report_models import to_report_response

REPO_ROOT = Path(__file__).resolve().parents[2]
NODE = shutil.which("node")


def _valid_snapshot() -> dict:
    report = _report_service([]).build_report(**_query())
    response = to_report_response(report)
    return {
        field: response.model_dump(mode="json")[field]
        for field in ("status", "research", "evidence", "interpretation", "strategy", "ideation")
    }


def _fingerprint(snapshot: dict) -> str:
    return snapshot_fingerprint(snapshot)


class TestCanonicalSnapshot:
    def test_integral_float_and_int_hash_identically(self) -> None:
        a = _valid_snapshot()
        b = json.loads(json.dumps(a))
        a["research"]["query"]["result_limit"] = 20
        b["research"]["query"]["result_limit"] = 20.0
        assert canonical_snapshot_bytes(a) == canonical_snapshot_bytes(b)

    def test_key_order_does_not_change_the_fingerprint(self) -> None:
        snapshot = _valid_snapshot()
        reordered = dict(reversed(list(snapshot.items())))
        assert _fingerprint(snapshot) == _fingerprint(reordered)

    def test_changed_content_changes_the_fingerprint(self) -> None:
        snapshot = _valid_snapshot()
        changed = json.loads(json.dumps(snapshot))
        changed["research"]["query"]["topic"] = "a different topic"
        assert _fingerprint(snapshot) != _fingerprint(changed)

    def test_persistence_metadata_is_excluded(self) -> None:
        snapshot = _valid_snapshot()
        with_metadata = dict(snapshot)
        with_metadata["persistence"] = {"status": "saved", "report_id": "x"}
        assert canonical_snapshot_bytes(snapshot) == canonical_snapshot_bytes(with_metadata)

    def test_evidence_numeric_facts_survive_js_roundtrip(self) -> None:
        """A real JavaScript JSON round trip must not create a false conflict."""
        assert NODE is not None, "node is required for the round-trip regression"
        snapshot = _valid_snapshot()
        # A ratio-like float and an integral float are the interesting cases.
        snapshot["evidence"]["patterns"][0]["ratio"] = 1.0
        if snapshot["evidence"]["patterns"][0]["matching_reference_ids"]:
            pass
        script = (
            "let data='';process.stdin.on('data',c=>data+=c);"
            "process.stdin.on('end',()=>{"
            "const parsed=JSON.parse(data);"
            "process.stdout.write(JSON.stringify(parsed));});"
        )
        completed = subprocess.run(
            [NODE, "-e", script],
            input=json.dumps(snapshot),
            capture_output=True,
            text=True,
            timeout=30,
            cwd=REPO_ROOT,
        )
        assert completed.returncode == 0, completed.stderr
        roundtripped = json.loads(completed.stdout)
        assert _fingerprint(snapshot) == _fingerprint(roundtripped)


class TestStrictValidation:
    def test_valid_snapshot_passes(self) -> None:
        ReportSnapshot.model_validate(_valid_snapshot())

    def test_unknown_field_rejected(self) -> None:
        snapshot = _valid_snapshot()
        snapshot["unexpected"] = True
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_non_finite_number_rejected(self) -> None:
        snapshot = _valid_snapshot()
        snapshot["evidence"]["patterns"][0]["ratio"] = float("inf")
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_unknown_citation_kind_rejected(self) -> None:
        snapshot = _valid_snapshot()
        if snapshot["interpretation"] is None or not snapshot["interpretation"]["interpretations"]:
            pytest.skip("fixture has no interpretations")
        snapshot["interpretation"]["interpretations"][0]["citations"] = [
            {"kind": "quantum", "observation_type": "x"}
        ]
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_brief_with_missing_parent_idea_rejected(self) -> None:
        snapshot = _valid_snapshot()
        if snapshot["ideation"] is None:
            pytest.skip("fixture has no ideation")
        snapshot["ideation"]["content_briefs"] = [
            {
                "idea_index": 999,
                "objective": "o",
                "format": "f",
                "hook": "h",
                "outline": ["a"],
                "citations": [{"kind": "pattern", "observation_type": "x"}],
            }
        ]
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_unsafe_reference_url_rejected(self) -> None:
        snapshot = _valid_snapshot()
        if not snapshot["research"]["references"]:
            pytest.skip("fixture has no references")
        snapshot["research"]["references"][0]["url"] = "javascript:alert(1)"
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_duplicate_reference_identity_rejected(self) -> None:
        snapshot = _valid_snapshot()
        if not snapshot["research"]["references"]:
            pytest.skip("fixture has no references")
        snapshot["research"]["references"].append(dict(snapshot["research"]["references"][0]))
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_boolean_for_integer_index_is_rejected(self) -> None:
        snapshot = _valid_snapshot()
        snapshot["research"]["query"]["result_limit"] = True
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_string_for_integer_count_is_rejected(self) -> None:
        snapshot = _valid_snapshot()
        if not snapshot["research"]["references"]:
            pytest.skip("fixture has no references")
        snapshot["research"]["references"][0]["source_rank"] = "1"
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_fact_citation_with_pattern_shape_is_rejected(self) -> None:
        snapshot = _valid_snapshot()
        snapshot["interpretation"] = {
            "model_provenance": {"provider": "p", "model": "m"},
            "interpretations": [
                {"statement": "x", "citations": [{"kind": "fact", "observation_type": "o"}]}
            ],
        }
        with pytest.raises(Exception) as excinfo:
            ReportSnapshot.model_validate(snapshot)
        assert not isinstance(excinfo.value, AttributeError)

    def test_citation_naming_missing_fact_is_rejected(self) -> None:
        snapshot = _valid_snapshot()
        if not snapshot["research"]["references"]:
            pytest.skip("fixture has no references")
        ref = {
            "source_code": snapshot["research"]["references"][0]["source_code"],
            "content_external_id": snapshot["research"]["references"][0]["content_external_id"],
        }
        snapshot["interpretation"] = {
            "model_provenance": {"provider": "p", "model": "m"},
            "interpretations": [
                {
                    "statement": "x",
                    "citations": [{"kind": "fact", "reference": ref, "field": "no_such_field"}],
                }
            ],
        }
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_citation_naming_missing_observation_is_rejected(self) -> None:
        snapshot = _valid_snapshot()
        if not snapshot["research"]["references"]:
            pytest.skip("fixture has no references")
        ref = {
            "source_code": snapshot["research"]["references"][0]["source_code"],
            "content_external_id": snapshot["research"]["references"][0]["content_external_id"],
        }
        snapshot["interpretation"] = {
            "model_provenance": {"provider": "p", "model": "m"},
            "interpretations": [
                {
                    "statement": "x",
                    "citations": [
                        {"kind": "observation", "reference": ref, "observation_type": "no_such"}
                    ],
                }
            ],
        }
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_pattern_citation_naming_missing_pattern_is_rejected(self) -> None:
        snapshot = _valid_snapshot()
        snapshot["interpretation"] = {
            "model_provenance": {"provider": "p", "model": "m"},
            "interpretations": [
                {"statement": "x", "citations": [{"kind": "pattern", "observation_type": "no_such"}]}
            ],
        }
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_invalid_calendar_date_is_rejected(self) -> None:
        snapshot = _valid_snapshot()
        snapshot["research"]["query"]["date_from"] = "2026-13-45"
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)

    def test_inconsistent_gap_index_is_rejected(self) -> None:
        snapshot = _valid_snapshot()
        if snapshot["strategy"] is None:
            pytest.skip("fixture has no strategy")
        snapshot["strategy"]["content_gaps"] = [
            {
                "statement": "g",
                "supporting_interpretation_indexes": [99],
                "citations": [{"kind": "pattern", "observation_type": "x"}],
            }
        ]
        with pytest.raises(Exception):
            ReportSnapshot.model_validate(snapshot)


class _ExpiringRecord:
    """Mimics an ORM instance whose attributes expire after commit/rollback.

    A real ``Session.commit()`` expires every loaded attribute; reading one
    then triggers a reload. If the session is closed or detached, that read
    raises. This fake makes the same failure observable without a database:
    any attribute read after ``expire()`` raises ``DetachedInstanceError``.
    """

    def __init__(self, fingerprint, origin="client_supplied", report_id=None) -> None:
        import uuid

        self._values = {
            "id": report_id or str(uuid.uuid4()),
            "payload_hash": fingerprint,
            "snapshot_origin": origin,
            "status": "completed",
            "report": {},
        }
        self._expired = False

    def expire(self) -> None:
        self._expired = True

    def __getattr__(self, name):
        if name.startswith("_"):
            raise AttributeError(name)
        if self._expired:
            raise RuntimeError(
                "DetachedInstanceError: attribute read after commit/rollback"
            )
        return self._values[name]


class _RecordingSession:
    def __init__(self, results=None) -> None:
        self._results = list(results or [])
        self.added = []
        self.commits = 0
        self.rollbacks = 0
        self.flushes = 0
        self.statements = []
        self.savepoints = 0

    def begin_nested(self):
        self.savepoints += 1
        return _Savepoint(self)

    def execute(self, statement, *args, **kwargs):
        self.statements.append(statement)
        if not self._results:
            raise AssertionError(f"unexpected statement: {statement}")
        return _FakeResult(self._results.pop(0))

    def add(self, record) -> None:
        self.added.append(record)

    def flush(self) -> None:
        self.flushes += 1
        for record in self.added:
            if getattr(record, "id", None) is None:
                record.id = "00000000-0000-4000-8000-0000000000aa"

    def commit(self) -> None:
        self.commits += 1
        for record in self.added:
            if hasattr(record, "expire"):
                record.expire()

    def rollback(self) -> None:
        self.rollbacks += 1
        for record in self.added:
            if hasattr(record, "expire"):
                record.expire()


class _Savepoint:
    def __init__(self, session) -> None:
        self._session = session

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb) -> bool:
        if exc_type is None:
            self._session.flush()
        return False


class _FakeResult:
    def __init__(self, scalar) -> None:
        self._scalar = scalar

    def scalar_one_or_none(self):
        return self._scalar


class _Membership:
    def __init__(self, active=True) -> None:
        self.user_id = "00000000-0000-4000-8000-000000000001"
        self.active = active


class _Row(_ExpiringRecord):
    """Mimics a committed ResearchReportRecord (attributes expire on commit)."""

    def __init__(self, fingerprint, origin="client_supplied", report_id=None):
        super().__init__(fingerprint, origin=origin, report_id=report_id)


def _save(session, snapshot, request_id="00000000-0000-4000-8000-000000000001"):
    from trendora.api.report_save import ReportSaveRequest, save_report_for_actor
    from trendora.research.recovery import issue_recovery_receipt
    from trendora.retention import report_source_deadline

    signing_key = "fictional-recovery-test-key-no-real-value"
    actor = _Membership().user_id
    body = ReportSaveRequest(
        schema_version=1, request_id=request_id, snapshot=snapshot,
        recovery_receipt=issue_recovery_receipt(
            actor_id=actor, request_id=UUID(str(request_id)), fingerprint=_fingerprint(snapshot),
            source_expires_at=report_source_deadline(snapshot, now=datetime.now(timezone.utc)),
            signing_key=signing_key,
        ),
    )
    with patch("trendora.api.report_save.get_settings", return_value=SimpleNamespace(
        report_recovery_signing_key=signing_key,
    )):
        return save_report_for_actor(session, actor_id=actor, body=body)


class TestInitialSaveToRecovery:
    """The committed initial save must be recoverable by the same actor+key."""

    def test_initial_save_then_recovery_acknowledges_without_a_second_insert(
        self, monkeypatch
    ) -> None:
        """A fresh generation, then a recovery with the same key, must return
        the original report id and insert nothing new."""
        import trendora.api.report_save as save_module

        from trendora.api.report_save import ReportSaveRequest, outcome_for

        snapshot = _valid_snapshot()
        fingerprint = _fingerprint(snapshot)
        request_id = uuid.uuid4()
        actor = _Membership().user_id

        # 1. Initial save: generation persists the row with the actor and key.
        first = _ExpiringRecord(fingerprint, origin="server_generated")
        first._values["id"] = "00000000-0000-4000-8000-0000000000c1"
        session = _RecordingSession([_Membership()])
        session.added.append(first)
        monkeypatch.setattr(
            save_module,
            "save_report_snapshot",
            lambda *a, **k: (first, True),
        )
        first_ack = _save(session, snapshot, request_id=str(request_id))
        assert first_ack.created is True
        first_id = first_ack.report_id

        # 2. Recovery with the same key: the lookup finds the committed row and
        #    returns the same id without inserting again.
        committed = _Row(fingerprint, origin="server_generated", report_id=first_id)
        session2 = _RecordingSession([_Membership(), committed])
        monkeypatch.setattr(
            save_module, "save_report_snapshot", lambda *a, **k: (committed, False)
        )
        second_ack = _save(session2, snapshot, request_id=str(request_id))
        assert second_ack.created is False
        assert second_ack.report_id == first_id
        assert session2.commits == 0
        assert session2.added == []


class TestSaveReplay:
    def test_first_save_commits_one_row(self) -> None:
        session = _RecordingSession([_Membership(), None])
        acknowledgment = _save(session, _valid_snapshot())
        assert acknowledgment.created is True
        assert acknowledgment.snapshot_origin == "client_supplied"
        assert acknowledgment.report_id
        assert session.commits == 1
        assert len(session.added) == 1

    def test_identical_replay_returns_the_existing_row(self) -> None:
        snapshot = _valid_snapshot()
        existing = _Row(_fingerprint(snapshot))
        session = _RecordingSession([_Membership(), existing])
        acknowledgment = _save(session, snapshot)
        assert acknowledgment.created is False
        assert acknowledgment.report_id == existing._values["id"]
        assert session.commits == 0
        assert session.rollbacks == 1

    def test_changed_payload_under_same_key_conflicts(self) -> None:
        from trendora.api.report_save import ReportSaveConflictErrorApi

        snapshot = _valid_snapshot()
        existing = _Row(_fingerprint(snapshot))
        session = _RecordingSession([_Membership(), existing])
        changed = json.loads(json.dumps(snapshot))
        changed["research"]["query"]["topic"] = "changed"
        with pytest.raises(ReportSaveConflictErrorApi):
            _save(session, changed)

    def test_inactive_membership_is_rejected(self) -> None:
        from trendora.api.errors import AuthInactiveError

        session = _RecordingSession([_Membership(active=False)])
        with pytest.raises(AuthInactiveError):
            _save(session, _valid_snapshot())


class TestAcknowledgmentSurvivesExpiry:
    """The acknowledgment must not read ORM attributes after the transaction."""

    def test_created_acknowledgment_is_readable_after_commit(self, monkeypatch) -> None:
        import trendora.api.report_save as module
        from trendora.api.report_save import outcome_for

        snapshot = _valid_snapshot()
        created_row = _ExpiringRecord(_fingerprint(snapshot))
        monkeypatch.setattr(
            module, "save_report_snapshot", lambda *a, **k: (created_row, True)
        )
        session = _RecordingSession([_Membership()])
        # Put the created row into the session so commit() expires it, exactly
        # as a real Session expires the instance it flushed.
        session.added.append(created_row)
        acknowledgment = _save(session, snapshot)
        assert acknowledgment.created is True
        assert session.commits == 1
        outcome = outcome_for(
            acknowledgment, request_id=UUID("00000000-0000-4000-8000-000000000001")
        )
        assert outcome.report_id
        assert outcome.snapshot_origin == "client_supplied"

    def test_replay_acknowledgment_is_readable_after_rollback(self, monkeypatch) -> None:
        import trendora.api.report_save as module
        from trendora.api.report_save import outcome_for

        snapshot = _valid_snapshot()
        existing = _Row(_fingerprint(snapshot))
        monkeypatch.setattr(
            module, "save_report_snapshot", lambda *a, **k: (existing, False)
        )
        session = _RecordingSession([_Membership()])
        session.added.append(existing)
        acknowledgment = _save(session, snapshot)
        assert acknowledgment.created is False
        outcome = outcome_for(
            acknowledgment, request_id=UUID("00000000-0000-4000-8000-000000000001")
        )
        assert outcome.report_id == existing._values["id"]
        assert outcome.snapshot_origin == "client_supplied"


class TestSaveRouteRoundTrip:
    """The real endpoint must save then recover the same id, one row only."""

    @pytest.mark.parametrize("include_receipt", [False, True])
    def test_missing_signing_key_refuses_new_source_recovery(self, monkeypatch, include_receipt):
        import trendora.api.report_save as save_module
        from trendora.api.deps import get_session as session_dep
        from trendora.research.recovery import issue_recovery_receipt
        from trendora.retention import report_source_deadline

        snapshot = _valid_snapshot()
        request_id = uuid.uuid4()
        receipt = issue_recovery_receipt(
            actor_id=_member().user_id, request_id=request_id,
            fingerprint=_fingerprint(snapshot),
            source_expires_at=report_source_deadline(snapshot, now=datetime.now(timezone.utc)),
            signing_key="fictional-recovery-test-key-no-real-value",
        )
        assert receipt is not None
        monkeypatch.setattr(save_module, "get_settings", lambda: SimpleNamespace(
            report_recovery_signing_key=None,
        ))
        session = _RecordingSession([_Membership(), None])
        app = create_test_app()
        app.dependency_overrides[session_dep] = lambda: session
        response = TestClient(app).post("/api/v1/research/reports/save", json={
            "schema_version": 1, "request_id": str(request_id), "snapshot": snapshot,
            "recovery_receipt": receipt if include_receipt else None,
        })
        assert response.status_code == 422
        assert response.json()["error"]["code"] == "invalid_report_snapshot"
        assert session.added == [] and session.commits == 0

    def test_route_save_then_recovery_does_not_duplicate(self, monkeypatch):
        import trendora.api.report_save as save_module
        from trendora.api.deps import get_session as session_dep

        snapshot = _valid_snapshot()
        request_id = str(uuid.uuid4())
        stored = {}

        def _fake_save(session, *, actor_id, request_id, snapshot, fingerprint, **kw):
            existing = stored.get((actor_id, request_id))
            if existing is None:
                row = _ExpiringRecord(fingerprint, origin="client_supplied")
                stored[(actor_id, request_id)] = row
                session.added.append(row)
                return row, True
            # A replay reads a fresh, un-expired row from the database.
            return _ExpiringRecord(
                fingerprint, origin="client_supplied", report_id=existing._values["id"]
            ), False

        monkeypatch.setattr(save_module, "save_report_snapshot", _fake_save)
        app = create_test_app()
        session = _RecordingSession([_Membership(), _Membership()])
        app.dependency_overrides[session_dep] = lambda: session
        client = TestClient(app)

        body = {"schema_version": 1, "request_id": request_id, "snapshot": snapshot}
        first = client.post("/api/v1/research/reports/save", json=body)
        assert first.status_code == 201, first.text
        first_id = first.json()["persistence"]["report_id"]

        second = client.post("/api/v1/research/reports/save", json=body)
        assert second.status_code == 200, second.text
        assert second.json()["persistence"]["report_id"] == first_id
        assert len(stored) == 1


class TestSaveRouteIsolation:
    def test_save_requires_authentication(self) -> None:
        app = create_test_app()
        # Remove the override so the real auth chain runs.
        app.dependency_overrides.clear()
        client = TestClient(app)
        response = client.post(
            "/api/v1/research/reports/save",
            json={"schema_version": 1, "request_id": "00000000-0000-4000-8000-000000000001", "snapshot": {}},
        )
        assert response.status_code == 401

    def test_save_constructs_no_research_or_ai_service(self, monkeypatch) -> None:
        import trendora.api.report_save as module

        def _boom(*args, **kwargs):  # pragma: no cover - must never run
            raise AssertionError("research/AI must not run during save")

        monkeypatch.setattr(module, "find_report_by_key", lambda *a, **k: None)
        app = create_test_app()
        app.dependency_overrides.clear()
        from trendora.api.auth import require_member

        app.dependency_overrides[require_member] = lambda: _member()
        client = TestClient(app)
        # Empty snapshot fails validation 422 without touching services.
        response = client.post(
            "/api/v1/research/reports/save",
            json={"schema_version": 1, "request_id": "00000000-0000-4000-8000-000000000001", "snapshot": {}},
        )
        assert response.status_code in (422, 503)


    def test_oversized_body_is_refused_before_validation(self) -> None:
        from trendora.api.report_save import REPORT_SAVE_BODY_LIMIT

        app = create_test_app()
        client = TestClient(app)
        oversized = {"schema_version": 1, "request_id": "00000000-0000-4000-8000-000000000001", "snapshot": {"blob": "a" * (REPORT_SAVE_BODY_LIMIT + 1)}}
        response = client.post("/api/v1/research/reports/save", json=oversized)
        assert response.status_code == 413
        assert response.json()["error"]["code"] == "report_request_too_large"

    def test_route_returns_controlled_422_for_invalid_snapshot(self) -> None:
        app = create_test_app()
        client = TestClient(app)
        snapshot = _valid_snapshot()
        snapshot["research"]["query"]["result_limit"] = True
        response = client.post(
            "/api/v1/research/reports/save",
            json={
                "schema_version": 1,
                "request_id": "00000000-0000-4000-8000-000000000001",
                "snapshot": snapshot,
            },
        )
        assert response.status_code == 422
        assert response.json()["error"]["code"] == "invalid_report_snapshot"


def _member():
    from tests.support.app import TEST_MEMBER

    return TEST_MEMBER
